language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

before_script: 
  - ./download_other_githubs.sh
  - ./install_other_githubs.sh

script: 
  - qmake NewickTest.pro
  - make --silent
  - ./NewickTest
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  - qmake NewickDemoDesktop.pro
  - make --silent debug
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)

