sudo: required
language: cpp
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # OCLint
  - ./install_oclint.sh

before_script: 
  - ./download_other_githubs.sh
  - ./install_other_githubs.sh

script: 
  - qmake NewickTest.pro
  - make
  - ./NewickTest
  - ./get_code_cov.sh
  - codecov
  - qmake NewickDemoDesktop.pro
  - make debug
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)

